security:
    encoders:
        Sindilojas\CobrancaBundle\Entity\Usuario: plaintext

    providers:
        main:
            entity: { class: SindilojasCobrancaBundle:Usuario, property: email }

    firewalls:
        login_firewall:
            pattern:   ^/login$
            anonymous: ~
        profile_firewall:
            pattern:   ^/_profiler
            anonymous: ~
        bar_firewall:
            pattern:   ^/_wdt
            anonymous: ~
        secured_area:
            pattern:    ^/
            form_login: 
                check_path: _login_check
                login_path: _login
                require_previous_session: false
                always_use_default_target_path: true
                default_target_path: /
            logout:
                path:   _logout
                target: _index
                
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }